name = "kesher-seo-worker"
main = "worker.js"
compatibility_date = "2024-03-29"

[placement]
mode = "smart"

# If the domain is hosted on Cloudflare, we can map this worker directly to the route:
# routes = [
#   { pattern = "kesher.saharoni.com/*", zone_name = "saharoni.com" }
# ]