#!/usr/bin/env python3
from pathlib import Path

path = Path('scripts/kesher_content_controller.py')
text = path.read_text(encoding='utf-8')
old = '''    def newest_video_state(self) -> dict[str, Any]:\n        payload = self.request(\n            "GET",\n            f"{self.api}/actions/artifacts?name={VIDEO_STATE_ARTIFACT}&per_page=100",\n        )\n        artifacts = [\n            row for row in (payload.get("artifacts") or [])\n            if isinstance(row, dict) and not row.get("expired")\n        ] if isinstance(payload, dict) else []\n        artifacts.sort(key=lambda row: str(row.get("created_at") or ""), reverse=True)\n        for artifact in artifacts:\n            archive_url = artifact.get("archive_download_url")\n            if not archive_url:\n                continue\n            try:\n                raw = self.download_artifact_archive(str(archive_url))\n                with zipfile.ZipFile(io.BytesIO(raw)) as archive:\n                    names = [name for name in archive.namelist() if name.endswith("state.json")]\n                    if not names:\n                        continue\n                    state = json.loads(archive.read(names[0]).decode("utf-8"))\n                    if isinstance(state, dict) and isinstance(state.get("items"), list):\n                        return state\n            except (zipfile.BadZipFile, json.JSONDecodeError, UnicodeDecodeError, KeyError):\n                continue\n        return {"version": 1, "items": []}\n'''
new = '''    def newest_video_state(self) -> dict[str, Any]:\n        payload = self.request(\n            "GET",\n            f"{self.api}/actions/artifacts?name={VIDEO_STATE_ARTIFACT}&per_page=100",\n        )\n        artifacts = [\n            row for row in (payload.get("artifacts") or [])\n            if isinstance(row, dict) and not row.get("expired")\n        ] if isinstance(payload, dict) else []\n        artifacts.sort(key=lambda row: str(row.get("created_at") or ""), reverse=True)\n        failures: list[str] = []\n        for artifact in artifacts:\n            artifact_id = artifact.get("id") or "unknown"\n            archive_url = artifact.get("archive_download_url")\n            if not archive_url:\n                failures.append(f"artifact {artifact_id}: missing archive_download_url")\n                continue\n            try:\n                raw = self.download_artifact_archive(str(archive_url))\n                with zipfile.ZipFile(io.BytesIO(raw)) as archive:\n                    names = [name for name in archive.namelist() if name.endswith("state.json")]\n                    if not names:\n                        failures.append(f"artifact {artifact_id}: missing state.json")\n                        continue\n                    state = json.loads(archive.read(names[0]).decode("utf-8"))\n                    if isinstance(state, dict) and isinstance(state.get("items"), list):\n                        return state\n                    failures.append(f"artifact {artifact_id}: unsupported state schema")\n            except ControllerError as exc:\n                failures.append(f"artifact {artifact_id}: {exc}")\n                continue\n            except (zipfile.BadZipFile, json.JSONDecodeError, UnicodeDecodeError, KeyError) as exc:\n                failures.append(f"artifact {artifact_id}: {type(exc).__name__}")\n                continue\n        if artifacts:\n            detail = " | ".join(failures[-5:]) or "no valid state artifact"\n            raise ControllerError(f"VIDEO_STATE_ARTIFACTS_UNRECOVERABLE: {detail}")\n        return {"version": 1, "items": []}\n'''
if text.count(old) != 1:
    raise SystemExit('newest_video_state target not unique')
path.write_text(text.replace(old, new, 1), encoding='utf-8')
