#!/usr/bin/env python3
import os
import sys
import json
import pickle
import argparse
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# Scopes required for uploading videos to YouTube
SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

def get_authenticated_service():
    """Authenticate and return the YouTube Service object."""
    credentials = None
    script_dir = os.path.dirname(os.path.abspath(__file__))
    token_path = os.path.join(script_dir, 'token.pickle')
    client_secrets_path = os.path.join(script_dir, 'client_secrets.json')
    
    # Load cached credentials if available
    if os.path.exists(token_path):
        try:
            with open(token_path, 'rb') as token:
                credentials = pickle.load(token)
        except Exception as e:
            print(f"Warning: Could not load cached token: {e}")
            
    # If credentials are not valid/loaded, do OAuth2 flow
    if not credentials or not credentials.valid:
        if credentials and credentials.expired and credentials.refresh_token:
            print("Refreshing expired YouTube API token...")
            try:
                credentials.refresh(Request())
            except Exception as e:
                print(f"Error refreshing credentials: {e}. Re-authenticating...")
                credentials = None
                
        if not credentials:
            if not os.path.exists(client_secrets_path):
                print(f"\n[ERROR] client_secrets.json not found in {script_dir}!")
                print("To upload videos to YouTube automatically, you must:")
                print("1. Go to Google Cloud Console (https://console.cloud.google.com)")
                print("2. Create a project, enable YouTube Data API v3")
                print("3. Configure OAuth Consent Screen (add yourself as test user)")
                print("4. Create OAuth Client ID credentials (Desktop app)")
                print("5. Download credentials and save them as 'scripts/client_secrets.json'")
                sys.exit(1)
                
            flow = InstalledAppFlow.from_client_secrets_file(client_secrets_path, SCOPES)
            credentials = flow.run_local_server(port=0)
            
        # Save credentials for future runs
        with open(token_path, 'wb') as token:
            pickle.dump(credentials, token)
            print("Successfully authenticated and cached token!")
            
    return build('youtube', 'v3', credentials=credentials)

def upload_video(youtube, video_path, title, description, tags, privacy_status="private", category_id="27"):
    """Upload a local video file to YouTube with metadata."""
    if not os.path.exists(video_path):
        print(f"Error: Video file not found at '{video_path}'")
        return None
        
    body = {
        'snippet': {
            'title': title,
            'description': description,
            'tags': tags,
            'categoryId': category_id,
            'defaultLanguage': 'he',
            'defaultAudioLanguage': 'he'
        },
        'status': {
            'privacyStatus': privacy_status,
            'selfDeclaredMadeForKids': False
        }
    }
    
    media = MediaFileUpload(video_path, chunksize=1024*1024, resumable=True, mimetype="video/*")
    
    print(f"\nStarting upload of: {video_path}")
    print(f"Title: {title}")
    print(f"Privacy: {privacy_status}")
    print(f"Category: {category_id} (Education/Counseling)")
    
    request = youtube.videos().insert(
        part="snippet,status",
        body=body,
        media_body=media
    )
    
    response = None
    while response is None:
        try:
            status, response = request.next_chunk()
            if status:
                print(f"Upload progress: {int(status.progress() * 100)}%")
        except Exception as e:
            print(f"An error occurred during upload: {e}")
            return None
            
    print(f"\n✓ Upload Complete!")
    print(f"Video URL: https://www.youtube.com/watch?v={response['id']}")
    return response['id']

def parse_metadata_file(filepath):
    """Load and parse the JSON metadata file generated by viral_creator.py."""
    if not os.path.exists(filepath):
        print(f"Error: Metadata file not found at '{filepath}'")
        return None
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:
        print(f"Error reading JSON metadata: {e}")
        return None

def main():
    parser = argparse.ArgumentParser(description="Upload video to YouTube channel with Gemini metadata")
    parser.add_argument("--video", type=str, required=True, help="Path to the local video file to upload")
    parser.add_argument("--meta", type=str, help="Path to the JSON metadata file generated by viral_creator.py")
    parser.add_argument("--title", type=str, help="Manually override the title")
    parser.add_argument("--description", type=str, help="Manually override the description")
    parser.add_argument("--tags", type=str, help="Comma-separated list of tags (overrides metadata tags)")
    parser.add_argument("--privacy", type=str, default="private", choices=["private", "unlisted", "public"], help="Privacy status (default: private)")
    parser.add_argument("--title-idx", type=int, default=1, choices=[1, 2, 3], help="Which of the 3 title ideas to use (default: 1)")
    
    args = parser.parse_args()
    
    title = args.title
    description = args.description
    tags = []
    
    if args.tags:
        tags = [t.strip() for t in args.tags.split(",") if t.strip()]
        
    # If metadata JSON file is provided, load details from it
    if args.meta:
        metadata = parse_metadata_file(args.meta)
        if metadata:
            yt_meta = metadata.get('youtube_metadata', {})
            
            # Select title
            if not title:
                titles = yt_meta.get('titles', [])
                if titles:
                    title = titles[args.title_idx - 1]
                    print(f"Selected Title {args.title_idx}: {title}")
                else:
                    title = "Untitled Video"
                    
            # Select description
            if not description:
                description = yt_meta.get('description', '')
                
            # Select tags
            if not tags:
                tags = yt_meta.get('tags', [])
                
    # Fallback to defaults or interactive prompts if metadata is missing
    if not title:
        title = input("Enter Video Title: ").strip()
    if not description:
        description = input("Enter Video Description: ").strip()
    if not tags:
        tags_input = input("Enter Video Tags (comma-separated): ").strip()
        tags = [t.strip() for t in tags_input.split(",") if t.strip()]
        
    # Standard validation
    if not title or not description:
        print("Error: Title and Description are required for upload.")
        sys.exit(1)
        
    # Authenticate and get YouTube service
    youtube = get_authenticated_service()
    if not youtube:
        print("Error: YouTube service authentication failed.")
        sys.exit(1)
        
    # Upload video
    upload_video(
        youtube=youtube,
        video_path=args.video,
        title=title,
        description=description,
        tags=tags,
        privacy_status=args.privacy
    )

if __name__ == "__main__":
    main()
