import { createMcpHandler } from "agents/mcp/server";
import { McpServer } from "@modelcontextprotocol/server";
import { z } from "zod";
import { getConflictPattern,getConversationPlan,getParentingResponsePlan,getAdhdParentingPlan,findKesherResource } from "./domain.mjs";

const annotations={readOnlyHint:true,destructiveHint:false,openWorldHint:false,idempotentHint:true};
const coupleTopic=z.enum(["money","household","parenting","extended_family","attention_connection","trust","intimacy","recurring_other"]);
const interactionSignal=z.enum(["criticism","defensiveness","withdrawal","pursuit","escalation","repetition","failed_repair","mistrust","overload"]);
const ageBand=z.enum(["preschool","elementary","preteen","teen"]);

const conflictInput=z.strictObject({topic:coupleTopic,interaction_signals:z.array(interactionSignal).min(1).max(4),goal:z.enum(["understand_pattern","deescalate","restart_conversation"])});
const conflictOutput=z.strictObject({pattern_label_he:z.string(),summary_he:z.string(),cycle_steps_he:z.array(z.string()).min(2).max(5),next_step_he:z.string(),avoid_he:z.array(z.string()).min(1).max(3)});
const conversationInput=z.strictObject({topic:coupleTopic,goal:z.enum(["express_hurt","request_change","discuss_money","discuss_household","discuss_parenting","set_family_boundary","ask_for_connection","discuss_intimacy","repair_after_conflict"]),emotional_intensity:z.enum(["low","moderate","high"]),interaction_risk:z.enum(["none","defensiveness","withdrawal","escalation"]),tone:z.enum(["gentle","direct","neutral"])});
const conversationOutput=z.strictObject({opening_he:z.string(),steps_he:z.array(z.string()).min(3).max(5),pause_phrase_he:z.string(),repair_phrase_he:z.string(),avoid_phrases_he:z.array(z.string()).min(1).max(4)});
const parentingInput=z.strictObject({age_band:ageBand,challenge:z.enum(["tantrum","boundaries","sibling_conflict","screens","bedtime","morning_routine","cooperation","transition","parent_disagreement","emotional_regulation","teen_connection"]),goal:z.enum(["deescalate","set_boundary","increase_cooperation","prepare_conversation","build_routine","repair_connection"]),response_style:z.enum(["calm_brief","collaborative","firm_kind"])});
const parentingOutput=z.strictObject({framing_he:z.string(),steps_he:z.array(z.string()).min(3).max(5),phrase_to_use_he:z.string(),phrase_to_avoid_he:z.string(),follow_up_he:z.string()});
const adhdInput=z.strictObject({age_band:ageBand,challenge:z.enum(["morning_routine","task_initiation","working_memory","transitions","organization","frustration","executive_function","impulsivity","screen_transition","gifted_adhd"]),goal:z.enum(["reduce_friction","build_external_support","start_task","complete_transition","increase_independence","recover_after_escalation"]),support_level:z.enum(["light","structured","high_structure"])});
const adhdOutput=z.strictObject({executive_function_frame_he:z.string(),environment_adjustments_he:z.array(z.string()).min(2).max(4),parent_steps_he:z.array(z.string()).min(3).max(5),phrase_he:z.string(),avoid_he:z.array(z.string()).min(1).max(3),professional_support_note_he:z.string()});
const resourceTopic=z.enum(["communication","recurring_conflict","money","household","parenting_alignment","trust","intimacy","extended_family","boundaries","tantrum","siblings","screens","bedtime","morning_routine","teen","emotional_regulation","adhd_morning","executive_function","organization","task_initiation","transitions","working_memory","impulsivity","frustration","gifted_adhd","other"]);
const resourceInput=z.strictObject({domain:z.enum(["couples","parenting","parenting_adhd"]),topic:resourceTopic,content_type:z.enum(["any","article"])});
const resourceOutput=z.strictObject({resources:z.array(z.strictObject({slug:z.string(),title:z.string(),url:z.string(),domain:z.string(),topics:z.array(z.string())})).max(3)});

const toolResult=(result)=>({structuredContent:result,content:[{type:"text",text:JSON.stringify(result)}]});
function createServer(){
  const server=new McpServer({name:"kesher-hebrew-relationship-parenting-tools",version:"0.2.0"},{instructions:"Kesher provides five read-only Hebrew tools for couple communication, practical parenting, attention/executive-function parenting support, and bounded Kesher resource discovery. Choose the narrowest fitting tool. Never diagnose ADHD or another condition, give medication/medical/legal/crisis guidance, enable surveillance/manipulation, or send raw narratives or identifiers to the MCP server."});
  server.registerTool("get_conflict_pattern",{title:"מיפוי דפוס קונפליקט זוגי",description:"Use when a Hebrew-speaking adult wants a structured explanation of a recurring couple-communication conflict and the situation can be reduced to a topic and observable interaction signals. Returns a non-diagnostic shared-cycle explanation and one practical next step. Do not use for parenting problems centered on a child, legal/divorce questions, medical or sexual-health advice, diagnosis, domestic violence or immediate danger, self-harm, surveillance, coercion/manipulation, generic information, or romantic writing.",inputSchema:conflictInput,outputSchema:conflictOutput,annotations},async a=>toolResult(getConflictPattern(a)));
  server.registerTool("get_conversation_plan",{title:"תכנון שיחה זוגית רגועה",description:"Use when a Hebrew-speaking adult wants a short plan for opening, repairing or de-escalating a difficult conversation with a partner after the topic and interaction risk are known. Do not use for child-focused parenting problems, legal/divorce negotiation, threats or violence, self-harm, medical or sexual-health advice, diagnosis, surveillance, coercion/manipulation, or pressure tactics.",inputSchema:conversationInput,outputSchema:conversationOutput,annotations},async a=>toolResult(getConversationPlan(a)));
  server.registerTool("get_parenting_response_plan",{title:"תוכנית תגובה הורית מעשית",description:"Use when a Hebrew-speaking parent wants practical, non-diagnostic guidance for a common parenting challenge such as boundaries, tantrums, sibling conflict, screens, bedtime, morning routines, cooperation, transitions, parent disagreement, emotional regulation, or connection with a teen. Do not use for diagnosing a child, medication or medical advice, self-harm, violence or immediate danger, legal/school-rights questions, covert surveillance, manipulation, or situations requiring emergency support.",inputSchema:parentingInput,outputSchema:parentingOutput,annotations},async a=>toolResult(getParentingResponsePlan(a)));
  server.registerTool("get_adhd_parenting_plan",{title:"תוכנית הורות לקשב ותפקודים ניהוליים",description:"Use when a Hebrew-speaking parent wants practical support for daily functioning commonly associated with attention or executive-function difficulties: morning routines, task initiation, working memory, transitions, organization, frustration, impulsivity, screen transitions, or giftedness with attention difficulties. The tool does not require or verify an ADHD diagnosis. Do not use to diagnose ADHD, score symptoms, recommend or change medication, give medical advice, handle self-harm or violence, answer legal/school-rights questions, or monitor a child covertly.",inputSchema:adhdInput,outputSchema:adhdOutput,annotations},async a=>toolResult(getAdhdParentingPlan(a)));
  server.registerTool("find_kesher_resource",{title:"מציאת תוכן רלוונטי באתר קשר",description:"Use only when the user explicitly asks for a Kesher article, guide, website resource, or further reading related to couples, parenting, or parenting around attention/executive-function challenges. Searches a bounded local Kesher content index and returns up to three relevant resources. Do not use as a general web search, provider search, medical/legal lookup, or as a promotional redirect when the user did not ask for a resource.",inputSchema:resourceInput,outputSchema:resourceOutput,annotations},async a=>toolResult(findKesherResource(a)));
  return server;
}
const mcpHandler=createMcpHandler(createServer,{route:"/mcp"});
export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==="/health")return Response.json({ok:true,service:"kesher-mcp",version:"0.2.0",tools:5});if(url.pathname==="/mcp"&&env?.MCP_RATE_LIMITER){const {success}=await env.MCP_RATE_LIMITER.limit({key:"mcp"});if(!success)return new Response("Too many MCP requests",{status:429,headers:{"Content-Type":"text/plain; charset=utf-8","Retry-After":"60"}});}return mcpHandler(request,env,ctx);}};
